name: PR Checks

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  check:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: actions/checkout@v4
        with:
          persist-credentials:n           false
      - run: echo hi
