name: PR Checks

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  check:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: swatinem/rust-cache@v2
        with:
          workspaces:n           src-tauri
      - run: echo hi
